/* 
  Filename: firebase.js
  Note: Firebase autogenerated code for importing into webapps
*/

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyD3e93KohU6HAmGDdYUBshcvr0ROUmedyI",
  authDomain: "movieteka-8a20c.firebaseapp.com",
  projectId: "movieteka-8a20c",
  storageBucket: "movieteka-8a20c.firebasestorage.app",
  messagingSenderId: "880165527669",
  appId: "1:880165527669:web:85c6f8a19e18d71a1b183c",
  measurementId: "G-NGRLLR8R33",
};

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
